osx_image: xcode10.1
language: objective-c
cache:
- cocoapods
install:
- travis_wait pod install --repo-update
before_script:
- set -o pipefail
script:
- xcodebuild -workspace MacDown.xcworkspace -scheme MacDown test | xcpretty
